export const AUTH_CHECK = 'AUTH_CHECK'
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGIN_SAMPLE = 'AUTH_LOGIN_SAMPLE'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_REFRESH_TOKEN = 'AUTH_REFRESH_TOKEN'
export const AUTH_RESET_PASSWORD = 'AUTH_RESET_PASSWORD'
export const AUTH_USER = 'AUTH_USER'
export const LOG_IN = 'LOG_IN';
export const SET_LOGGED_IN_STATE = 'SET_LOGGED_IN_STATE';
export const AUTH_LOGIN_GOOGLE = 'AUTH_LOGIN_GOOGLE'
export const AUTH_ALERT = 'AUTH_ALERT'
export const AUTH_REGISTER = 'AUTH_REGISTER'
export default {
  AUTH_CHECK,
  AUTH_LOGIN,
  AUTH_LOGIN_SAMPLE,
  AUTH_LOGOUT,
  AUTH_REFRESH_TOKEN,
  AUTH_RESET_PASSWORD,
  AUTH_USER,
  AUTH_LOGIN_GOOGLE,
  AUTH_ALERT,
  LOG_IN,
  SET_LOGGED_IN_STATE,
  AUTH_REGISTER
}
