export const AUTH_CHECK = 'AUTH_CHECK'
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_REFRESH_TOKEN = 'AUTH_REFRESH_TOKEN'
export const AUTH_RESET_PASSWORD = 'AUTH_RESET_PASSWORD'
export const AUTH_USER = 'AUTH_USER'
export const GET_INPUT = 'GET_INPUT'
export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION'
export const GET_NEARBY_DRIVERS = 'GET_NEARBY_DRIVERS'
export const GET_INTERVAL_BOOK = 'GET_INTERVAL_BOOK'
export const TOGGLE_SEARCH_RESULT = 'TOGGLE_SEARCH_RESULT'
export const GET_ADDRESS_PREDICTIONS = 'GET_ADDRESS_PREDICTIONS'
export const GET_SELECTED_ADDRESS = 'GET_SELECTED_ADDRESS'
export const CLEAR_SELECTED_ADDRESS = 'CLEAR_SELECTED_ADDRESS'
export const GET_DISTANCE_MATRIX = 'GET_DISTANCE_MATRIX'
export const GET_MOBIL_AVAILABLE = 'GET_MOBIL_AVAILABLE'
export const GET_SELECTED_CAR = 'GET_SELECTED_CAR'
export const BOOK_CAR = 'BOOK_CAR'
export const BOOKING_CANCELED = 'BOOKING_CANCELED'
export const BOOKING_CONFIRMED = 'BOOKING_CONFIRMED'
export const GET_FARE = 'GET_FARE'
export const UPDATE_LOCATION = 'UPDATE_LOCATION'


export default {
  AUTH_CHECK,
  AUTH_LOGIN,
  AUTH_LOGOUT,
  AUTH_REFRESH_TOKEN,
  AUTH_RESET_PASSWORD,
  AUTH_USER,
  GET_INPUT,
  GET_CURRENT_LOCATION,
  GET_INTERVAL_BOOK,
  GET_NEARBY_DRIVERS,
  TOGGLE_SEARCH_RESULT,
  GET_ADDRESS_PREDICTIONS,
  GET_SELECTED_ADDRESS,
  CLEAR_SELECTED_ADDRESS,
  GET_DISTANCE_MATRIX,
  GET_MOBIL_AVAILABLE,
  GET_SELECTED_CAR,
  BOOK_CAR,
  BOOKING_CANCELED,
  BOOKING_CONFIRMED,
  GET_FARE
}
