export const GET_PROMO = 'GET_PROMO'
export const GET_TYPECAR = 'GET_TYPECAR'
export const GET_SETTINGS = 'GET_SETTINGS'
export const SELECTED_TYPE_CAR = 'SELECTED_TYPE_CAR'
export const GET_RENT_PACKAGE = 'GET_RENT_PACKAGE'
export default {
  GET_PROMO,
  GET_TYPECAR,
  GET_SETTINGS,
  GET_RENT_PACKAGE,
  SELECTED_TYPE_CAR
}
